workflows:
  infinity-browser-x:
    name: Infinity Browser X Build

    max_build_duration: 120

    environment:
      android_signing:
        - infinity_keystore

    scripts:
      - name: Build Android APK
        script: |
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk
